# Generated by Django 3.1.7 on 2021-03-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=280)),
                ('author', models.CharField(max_length=20)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
