# Generated by Django 3.1.7 on 2021-03-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
