# Generated by Django 3.1.7 on 2021-03-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortenedurl_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
